import {
    ApartmentOutlined,
    HomeOutlined,
    InfoCircleOutlined,
    SettingOutlined,
    RocketOutlined,
    UserOutlined,
} from '@ant-design/icons';
import LoadableComponent from '../Loadable/index';

const appRouters: any = [
    {
        key: 'app-layout',
        path: '/admin',
        exact: true,
        name: 'home',
        permission: '',
        title: 'Home',
        component: LoadableComponent(() => import('../Layout/AppLayout')),
        isLayout: true,
        showInMenu: false,
    },
    {
        key: 'dashboard-screen',
        path: '/admin/dashboard',
        name: 'dashboard',
        permission: '',
        title: 'Dashboard',
        icon: HomeOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Dashboard')),
    },
    {
        key: 'logout-screen',
        path: '/admin/logout',
        permission: '',
        title: 'Logout',
        name: 'logout',
        showInMenu: false,
        component: LoadableComponent(() => import('../Logout')),
    },
    {
        key: 'exception-screen',
        path: '/exception?:type',
        permission: '',
        title: 'exception',
        name: 'exception',
        showInMenu: false,
        component: LoadableComponent(() => import('../../scenes/Exception')),
    },
    {
        key: 'department-detail-screen',
        path: '/admin/departments/:departmentId',
        permission: '',
        title: 'Department Detail',
        name: 'department-detail',
        showInMenu: false,
        component: LoadableComponent(() => import('../../scenes/Departments/components/DepartmentDetail')),
    },
    {
        key: 'departments-screen',
        path: '/admin/departments',
        name: 'departments',
        permission: '',
        title: 'Departments',
        icon: ApartmentOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Departments')),
    },
    {
        key: 'employee-screen',
        path: '/admin/employee',
        permission: '',
        title: 'Employee',
        name: 'employee',
        icon: UserOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Employee')),
    },
    {
        key: 'employees-detail-edit-screen',
        path: '/admin/employee/:id/edit',
        permission: '',
        title: 'EmployeeDetailEdit',
        name: 'employee-detal-edit',
        showInMenu: false,
        component: LoadableComponent(() => import('../../scenes/Employee/components/EmployeesDetail')),
    },
    {
        key: 'employees-detail-add-screen',
        path: '/admin/employee/add',
        permission: '',
        title: 'EmployeeDetailAdd',
        name: 'employee-detail-add',
        showInMenu: false,
        component: LoadableComponent(() => import('../../scenes/Employee/components/EmployeesDetail')),
    },
    {
        key: 'kanban-screen',
        path: '/admin/kanban',
        permission: '',
        title: 'Kanban',
        name: 'kanban',
        showInMenu: true,
        icon: SettingOutlined,
        component: LoadableComponent(() => import('../../scenes/Kanban/index')),
    },
    {
        key: 'my-page-screen',
        path: '/admin/mypage',
        permission: '',
        title: 'MyPage',
        name: 'mypage',
        icon: RocketOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/MyPage')),
    },
    {
        key: 'about-screen',
        path: '/admin/about',
        permission: '',
        title: 'About',
        name: 'about',
        icon: InfoCircleOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/About')),
    },
];

export default appRouters;
